- name: Install preinstall oracle
  get_url:
    url: https://yum.oracle.com/repo/OracleLinux/OL7/latest/x86_64/getPackage/oracle-database-preinstall-{{oracledb_version}}-1.0-1.el7.x86_64.rpm
    dest: /root
  when: ansible_distribution == "CentOS"

- name: Preinstall oracle
  shell: 
    cmd: yum -y localinstall oracle-database-preinstall-{{oracledb_version}}-1.0-1.el7.x86_64.rpm
    chdir: /root
  when: ansible_distribution == "CentOS"

- name: OracleLinux config yum.repos.d 
  shell: 
    cmd: wget http://public-yum.oracle.com/public-yum-ol7.repo
    chdir: /etc/yum.repos.d
  when: ansible_distribution == "OracleLinux"

- name: OracleLinux yum install
  shell:  yum repolist all
  when: ansible_distribution == "OracleLinux"

- name: Download oracle
  get_url:
    url: https://download.oracle.com/otn-pub/otn_software/db-express/oracle-database-{{oracledb_server_meta.community.lower_name}}-{{oracledb_version}}c-1.0-1.x86_64.rpm
    dest: /root

- name: Install oracle
  shell: 
    cmd: yum -y localinstall oracle-database-{{oracledb_server_meta.community.lower_name}}-{{oracledb_version}}-1.0-1.x86_64.rpm
    chdir: /root

- name: show config file 
  shell: echo "/etc/init.d/oracle-{{oracledb_server_meta.community.lower_name}}-{{oracledb_version}}"

# Oracle configuration
- name: configure oracle database,listener
  shell: (echo {{oracledb_password}}; echo {{oracledb_password}};) | /etc/init.d/oracle-{{oracledb_server_meta.community.lower_name}}-{{oracledb_version}} configure

- name: change to oracle
  shell: su oracle

- name: set database directory
  blockinfile:
    path: /home/oracle/.bash_profile
    owner: oracle
    block: |
      export ORACLE_BASE=/opt/oracle 
      export ORACLE_HOME=/opt/oracle/product/{{oracledb_version}}/dbhome{{oracledb_server_meta.community.name}}
      export ORACLE_SID={{oracledb_server_meta.community.name}}
      export PATH=$PATH:$ORACLE_HOME/bin

- name: source env
  shell: source /home/oracle/.bash_profile
# Rename oracle service and  restart oracle

- name: Reload service
  shell: systemctl daemon-reload

- name: Restart oracle.service
  service:
    name: oracle-xe-18c
    state: restarted
    enable: yes

- name: Rename service
  shell: ln -sf /run/systemd/generator.late/oracle-{{oracledb_server_meta.community.lower_name}}-{{oracledb_version}}.service  /lib/systemd/system/oracle.service

- name: set soft link
  shell: |
    ln -sf /opt/oracle  /data/oracle
    ln -sf /opt/oracle/config /data/oracle/config
    ln -sf /opt/oracle/cfgtoollogs/dbca/{{oracle_serverdb_meta.community.name}}   /data/logs

# check service state
- name: Check oracle Service     
  shell: systemctl status oracle | grep Active*
  register: check_oracle_service
  notify: check_oracle_service
 
# Check version,
# must use sudo sh -c to solve the no-root permission
- name: check version
  shell: sudo sh -c "echo ` rpm -qa |grep oracle-database-xe` >> /data/logs/install_version.txt"
