---
- hosts: localhost
  remote_user: root
  roles:
    - role_oracledb

  vars_prompt:
    - name: 'oracledb_selection'
      prompt: "\n Have you reviewed and accept the Oracle License Agreement https://www.oracle.com/technetwork/licenses/standard-license-152015.html#licenseContent [ y/n ] \n\n
      Yes, I have reviewed and accept the Oracle License Agreement \n
      No, I have not reviewed and accept the Oracle License Agreement\n"
      private: no

    - name: 'oracledb_version_selection'
      prompt: "\nPlease choose the number for OracleDB version [ 1/2 ] \n\n
      1: oracle database ee 18c(not support)\n
      2: oracle database ee 19c(support)\n"
      private: no
      default: 1

  vars:
    oracledb_select:
      'Y': True
      'y': True
      'N': False
      'n': False
    oracledb_official: "{{oracledb_select[oracledb_selection]}}"

  vars:
    oracledb_version_select:
      '1': '18c'
      '2': '19c'
    oracledb_version: "{{oracledb_version_select[oracledb_version_selection]}}"

  pre_tasks:
    - debug:
        msg: Will install oracle {{oracledb_version}} database

  roles:
    - {role: role_oracledb, tags: "role_oracledb"}  
